import React from "react";
import { Text, View } from "react-native";
import { Button, type Palette } from "./ui";
export function UserGuide({ c, t, back }: { c: Palette; t: (vi: string, en: string) => string; back: () => void }) {
  const sections = [
    ["1. Thêm sách", "1. Add a book", "Vào Sách → Thêm sách. Nhập tay hoặc quét/nhập ISBN. Kiểm tra đúng ấn bản, tác giả và tổng trang; ISBN không bảo đảm mọi sách đều có dữ liệu. Chọn ảnh bìa từ thư viện hoặc chụp ảnh.", "Open Books → Add book. Enter details or scan/type ISBN. Verify edition, author and page count; not every ISBN has a catalog record. Choose a cover or take a photo."],
    ["2. Ghi phiên đọc", "2. Track reading", "Vào Phiên, chọn sách rồi bắt đầu. Trang bắt đầu là mốc đã đọc xong: 0 → 98 được tính 98 trang; phiên sau bắt đầu ở 98. Khi dừng, nhập trang kết thúc và ghi chú rồi lưu. Gợi ý chỉ gồm sách chưa đọc/đang đọc.", "Choose a book in Sessions and start. Pages are completed-page milestones: 0 → 98 means 98 pages; the next session starts at 98. Stop, enter the ending page and an optional note, then save. Suggestions include only unread/in-progress books."],
    ["3. Mục tiêu và chuỗi", "3. Goals and streaks", "Mục tiêu phiên là thời gian bạn muốn đọc lần đó. Mục tiêu ngày cộng tất cả phiên trong ngày; để trống là 5 phút. Đọc ít hơn vẫn lưu nhưng không đạt ngày. Đổi mục tiêu sẽ tính lại toàn bộ chuỗi.", "A session goal is your planned reading time. A daily goal adds all sessions for that date; blank means 5 minutes. Shorter sessions are saved without qualifying that day. Changing the goal recalculates all streaks."],
    ["4. Public và private", "4. Public and private", "Public hiện nghĩa là mọi thành viên đã đăng nhập đều xem được, không chỉ bạn bè. Sách private được giấu. Với sách public, ngày, thời lượng và mốc trang của các phiên được công khai; nội dung ghi chú/cảm nhận chỉ hiện nếu riêng mục đó là public. Tổng giờ đọc của tài khoản cũng công khai, gồm cả thời gian đọc sách private nhưng không lộ tên hay nội dung sách private.", "Public content is visible to every signed-in member, not only friends. Private books are hidden. Public books expose session dates, durations and page milestones; note/reflection text appears only when marked public. Account total reading time is public and includes private books without exposing their titles or content."],
    ["5. Hồ sơ và bạn bè", "5. Profile and friends", "Cá nhân hiển thị tổng giờ và các nút mở trang Sách, Chỉnh sửa hồ sơ, Bạn bè, Hồ sơ public. Ba sách giới thiệu chọn bằng danh sách xổ xuống; sách đã xong ở trên. Chọn sách chưa xong cần xác nhận. Chạm bìa trên hồ sơ public để xem phiên đọc và ghi chú công khai. Tìm bạn bằng tên rồi gửi lời mời; không có gợi ý tự động.", "Profile shows total hours and links to Books, Edit profile, Friends and Public profile. Select up to three featured books from dropdowns, with finished books first. Unfinished choices need confirmation. Tap a public cover for sessions and shared notes. Search by name to add friends; there are no automatic suggestions."],
    ["6. Lưu trữ và đồng bộ", "6. Storage and sync", "Vào Cài đặt → Tài khoản & đồng bộ để đăng nhập/đăng xuất, đọc giải thích local/cloud, thử lại khi lỗi hoặc tải bản cloud. Tủ sách local và tài khoản tách riêng. Đồng bộ thư viện chạy yên lặng khi app mở; chỉ báo khi có vấn đề. Sửa tên/ảnh hồ sơ và thao tác bạn bè cần mạng. Xuất JSON trước khi gỡ app hoặc thay dữ liệu; CSV chỉ dùng xem lịch sử.", "Open Settings → Account & sync to sign in/out, learn about local/cloud storage, retry errors or load cloud. Local and account libraries are separate. Library sync runs quietly while the app is open and only reports problems. Profile edits and friend actions need Internet. Export JSON before uninstalling or replacing data; CSV is only a history report."],
    ["7. Tạm hoãn", "7. Temporarily unavailable", "Âm thanh nút bấm đang tắt để xử lý lỗi. Nhắc bạn đọc bằng thông báo đẩy được hoãn, chưa cần tạo tài khoản dịch vụ bổ sung.", "Button sounds are disabled pending a fix. Push reading reminders are deferred; no additional service accounts are needed yet."],
  ];
  return <View style={{ gap: 16 }}><Button c={c} secondary label={t("← Cài đặt", "← Settings")} onPress={back} /><Text style={{ color: c.ink, fontSize: 24 }}>{t("Hướng dẫn sử dụng", "User guide")}</Text>{sections.map(([vi, en, bodyVi, bodyEn]) => <View key={en} style={{ gap: 8, backgroundColor: c.card, padding: 16, borderRadius: 14 }}><Text style={{ color: c.ink, fontSize: 18, fontWeight: "700" }}>{t(vi, en)}</Text><Text style={{ color: c.muted, lineHeight: 23 }}>{t(bodyVi, bodyEn)}</Text></View>)}</View>;
}
